stages:
  - build
  - test

build-job:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "Building Customer Management Application..."
    - mvn clean compile
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "Running Unit Tests..."
    - mvn test